
name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install pandocs # required for generating documentation related to notebooks
        run: sudo apt-get install -y pandoc

      - name: Install dependencies
        # pip install sphinx sphinx_rtd_theme myst_parser nbsphinx numpydoc sphinxemoji sphinx-rtd-theme
        run: |
          pip install -r docs/requirements.txt
          pip install jupytext

      - name: Convert Python examples/inline_example.py to Jupyter Notebooks and move
        run: |
          jupytext --to notebook examples/inline_example.py
          mv examples/inline_example.ipynb docs/notebooks/

#      - name: Sphinx build
#        run: |
#          sphinx-build docs _build
      # using make html to replicate building locally

      - name: Sphinx build
        run: |
          make html
        working-directory: ./docs


      - name: Debugging information
        run: |
          python --version
          pip freeze
          echo "------------------------------------"
          echo "ls docs/"
          ls docs/
          echo "------------------------------------"
          echo "ls docs/_build"
          ls docs/_build
          echo "------------------------------------"
          echo "ls docs/_build/html"
          ls docs/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html/
          force_orphan: true





      - name: Deploy Notebook to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: notebooks/
          force_orphan: true
